In [0]:
import numpy as np

In [0]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y

In [3]:
Z

array([[1, 1],
       [1, 1]])

In [4]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [0]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)

In [6]:
Z

array([[2, 1],
       [1, 2]])